migrations:
  0->0: [0,0]
  0->1: [0,1]
  0->2: [0,2]
  1->1: [1,1]
  1->0: [1,0]
  1->2: [1,2]
  2->2: [2,2]
  2->0: [2,0]
  2->1: [2,1]
  # 10->10: [10,10]
  # 11->11: [11,11]
  # 11->10: [11,10]
  # 10->11: [10,11]
axis:
  xlabel: "P mínimo (GeV/c)"
  title: "Pureza vs corte en fotón P"
metric: "purity"